services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.mlapp
    ports:
      - "9000:9000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data

    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:6000
    depends_on:
      - mlflow
    networks:
      - carprices-network

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:6000"
    volumes:
      - mlflow-data:/mlflow
    networks:
      - carprices-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/rules:/etc/prometheus/rules
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

    # Add extra_hosts to allow accessing host machine from container
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - carprices-network
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    networks:
      - carprices-network
    depends_on:
      - prometheus

networks:
  carprices-network:
    driver: bridge

volumes:
  mlflow-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local