FROM python:3.12.3

WORKDIR /mlflow


RUN pip install --no-cache-dir \
    mlflow==2.20.2

# Create directory for artifacts
RUN mkdir -p /mlflow/artifacts

# Expose MLflow tracking server port
EXPOSE 6000

# Start MLflow server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "6000", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlflow/artifacts"]