FROM python:3.12.3

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p models data/raw data/processed data/external /app/logs

ENV LOG_DIR=/app/logs
ENV PYTHONPATH=/app
ENV FLASK_APP=src/predict_api.py

EXPOSE 9000

CMD ["python", "src/predict_api.py"]