global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml" # * allows almost any file to prevent strict rules.

scrape_configs:
  - job_name: 'ml-app'
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['app:9000']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'model-training' 
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'training:8002'
    metrics_path: /metrics
    scheme: http
    scrape_timeout: 3s